#!/usr/bin/env bash
# Transfers a file from our client to a server
file=$1
IP=$2
user=$3
ssh_key=$4

if [[ $# -lt 3 ]]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp "$1" "$3"@"$2":~/
fi
