#!/usr/bin/env bash
# Installs, configures and start server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i "s/location \//location \/redirect_me/" /etc/nginx/sites-enabled/default
sed -i "s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com/watch?v=QH2-TGU1wu4;/" /etc/nginx/sites-enabled/default

SERVER="error_page 404 /custom_404.html;\nlocation = /custom_404.html { root /var/www/html; internal; }"
sed -i "/location \/redirect_me/i $SERVER" /etc/nginx/sites-enabled/default

service nginx reload
