#!/usr/bin/env bash
# Configure new nginx server with custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
HEADER="add_header X-Served-By $HOSTNAME;"
sed -i "/sendfile on;/a $HEADER" /etc/nginx/nginx.conf
service nginx restart
