#!/usr/bin/env bash
# Display 'Best School' 10 times and on 9th iteration display Hi
count=1
while [[ "$count" -le 10 ]]; do
        if [[ "$count" -eq 9 ]]; then
                echo "Best School"
                echo "Hi"
                count=$((count + 1))
        else
                echo "Best School"
                count=$((count + 1))
        fi
done
