#!/usr/bin/env bash
# Script that runs an Apache on given container and returns a page containing Hello Holberton when querying the root of it

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
