#!/usr/bin/env bash
# Configuring SSH Client to connect to server without password
Host myServer
        HostName 54.90.17.93
        User ubuntu
        IdentityFile ~/.ssh/school
        PasswordAuthentication no
